_target_: src.datamodules.unsmile_datamodule.UnsmileDataModule

data_dir: ${data_dir}
batch_size: 64
train_data_path: ${data_dir}/korean_unsmile_data/unsmile_train_v1.0.tsv
valid_data_path: ${data_dir}/korean_unsmile_data/unsmile_valid_v1.0.tsv
pretrained_model: ${pretrained_path}
train_val_test_split: 0.8, 0.1, 0.1
num_workers: 0
pin_memory: False
